// USER ACTION TYPES
export const LOADING_USERS = 'LOADING_USERS',
  SET_AUTHENTICATED = 'SET_AUTHENTICATED',
  SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED',
  SET_USER = 'SET_USER'

// DATA ACTION TYPES
export const CLEAR_ERRORS = 'CLEAR_ERRORS',
  SET_ERRORS = 'SET_ERRORS'

// UI ACTION TYPES
