// USER ACTION TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED',
SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED',
LOADING_USERS='LOADING_USERS',
SET_USER='SET_USER';


// DATA ACTION TYPES
export const SET_ERRORS = 'SET_ERRORS',
CLEAR_ERRORS = 'CLEAR_ERRORS';


// UI ACTION TYPES